services:
  expressjs:
    image: node:20
    container_name: expressjs
    working_dir: /app
    volumes:
      - ./:/app
      - /app/node_modules # node_modules はコンテナ内で管理
    ports:
      - '3000:3000'
    # 初期設定も含めて実行
    command: bash -c "npm install -g typescript tsc-alias && npm i && npm run build && npm run start"
    restart: always
